### ISSUE TITLE
Missing library file

### ISSUE THREAD

**Issue by hsqaihkl** [giorgiomarcias/distance_transform#2]
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/extern/DopeVector ${CMAKE_CURRENT_BINARY_DIR}/lib_dope_vector)
there no file in this folder！

**Comment by giorgiomarcias** [comment]
Hi, did you synced the submodule? `git clone --recurse-submodules https://github.com/giorgiomarcias/distance_transform.git`

**Comment by hsqaihkl** [comment]
sorry，I did't！I just download zip files directly!

**Comment by giorgiomarcias** [comment]
No problem 🙂
